// import { locales } from 'app/i18n/settings';
import { getServerSession } from 'next-auth';
import { Lato, Sora } from 'next/font/google';
import { MainLayout } from 'presentation/layouts/Main';
import { LangPropsPage } from 'types';
import { authOptions } from '../api/auth/[...nextauth]/route';

// export async function generateStaticParams() {
//   return locales.map((locale) => ({ lang: locale }));
// }

export const metadata = {
  title: 'Cine Share',
  description: 'Generated by create next app',
};

const lato = Lato({
  subsets: ['latin'],
  variable: '--text-font',
  fallback: ['sans serif'],
  weight: ['700', '400', '900'],
});

const sora = Sora({
  subsets: ['latin'],
  variable: '--title-font',
  fallback: ['sans serif'],
  weight: ['700', '600', '500', '400'],
});

export default async function RootLayout({
  children, params: { lang },
}: LangPropsPage) {
  const session = await getServerSession(authOptions);

  return (
    <html lang={lang} className={`${lato.variable} ${sora.variable}`}>
      <body>
        <MainLayout session={session}>
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
