import { getServerSession } from 'next-auth';
import { MainLayout } from 'presentation/layouts/Main';
import { authOptions } from './api/auth/[...nextauth]/route';

export const metadata = {
  title: 'Cine Share',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <MainLayout session={session}>
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
