import { Suspense } from 'react';

export default function Home() {
  return (
    <Suspense fallback={<p>Loading...</p>}>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
      <h1>Play</h1>
    </Suspense>
  );
}
